=== SNodeC/mqttsuite/lib/mapping-schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "required": [
    "mapping"
  ],
  "properties": {
    "meta": {
      "type": "object",
      "properties": {
        "version": { "type": "string", "description": "Auto-generated timestamp or ID" },
        "comment": { "type": "string", "description": "User description of this configuration state" },
        "author": { "type": "string" },
        "created": { "type": "string", "format": "date-time" }
      }
    },
    "discover_prefix": {
      "type": "string",
      "default": ""
    },
    "connection": {
      "type": "object",
      "properties": {
        "keep_alive": {
          "type": "integer",
          "default": 60
        },
        "client_id": {
          "type": "string",
          "default": ""
        },
        "clean_session": {
          "type": "boolean",
          "default": true
        },
        "will_topic": {
          "type": "string",
          "default": ""
        },
        "will_message": {
          "type": "string",
          "default": ""
        },
        "will_qos": {
          "type": "integer",
          "default": 0,
          "minimum": 0,
          "maximum": 2
        },
        "will_retain": {
          "type": "boolean",
          "default": false
        },
        "username": {
          "type": "string",
          "default": ""
        },
        "password": {
          "type": "string",
          "default": ""
        }
      },
      "default": {
        "keep_alive": 60,
        "client_id": "",
        "clean_session": true,
        "will_topic": "",
        "will_message": "",
        "will_qos": 0,
        "will_retain": false,
        "username": "",
        "password": ""
      }
    },
    "mapping": {
      "$id": "https://www.vchrist.at/mqttmapper/schemas/mapping",
      "type": "object",
      "required": [
        "topic_level"
      ],
      "properties": {
        "plugins": {
          "$id": "https://www.vchrist.at/mqttmapper/schemas/plugins",
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "topic_level": {
          "$id": "https://www.vchrist.at/mqttmapper/schemas/topic_level",
          "oneOf": [
            {
              "$ref": "#/$defs/topic_level"
            },
            {
              "type": "array",
              "items": {
                "$ref": "#/$defs/topic_level"
              }
            }
          ],
          "$defs": {
            "topic_level": {
              "type": "object",
              "required": [
                "name"
              ],
              "anyOf": [
                {
                  "required": [
                    "topic_level"
                  ]
                },
                {
                  "required": [
                    "subscription"
                  ]
                }
              ],
              "properties": {
                "name": {
                  "type": "string",
                  "pattern": "^(?:[^#+]{2,}|.)$",
                  "minLength": 1
                },
                "topic_level": {
                  "$ref": "#"
                },
                "subscription": {
                  "type": "object",
                  "properties": {
                    "qos": {
                      "type": "integer",
                      "minimum": 0,
                      "maximum": 2,
                      "default": 0
                    },
                    "type": {
                      "type": "string",
                      "default": ""
                    }
                  },
                  "anyOf": [
                    {
                      "$ref": "#/$defs/mapping_static"
                    },
                    {
                      "$ref": "#/$defs/mapping_value"
                    },
                    {
                      "$ref": "#/$defs/mapping_json"
                    }
                  ]
                }
              }
            },
            "mapping_static": {
              "type": "object",
              "required": [
                "static"
              ],
              "properties": {
                "static": {
                  "oneOf": [
                    {
                      "$ref": "#/$defs/static_mapping"
                    },
                    {
                      "type": "array",
                      "items": {
                        "$ref": "#/$defs/static_mapping"
                      }
                    }
                  ]
                }
              }
            },
            "mapping_value": {
              "type": "object",
              "required": [
                "value"
              ],
              "properties": {
                "value": {
                  "oneOf": [
                    {
                      "$ref": "#/$defs/template_mapping"
                    },
                    {
                      "type": "array",
                      "items": {
                        "$ref": "#/$defs/template_mapping"
                      }
                    }
                  ]
                }
              }
            },
            "mapping_json": {
              "type": "object",
              "required": [
                "json"
              ],
              "properties": {
                "json": {
                  "oneOf": [
                    {
                      "$ref": "#/$defs/template_mapping"
                    },
                    {
                      "type": "array",
                      "items": {
                        "$ref": "#/$defs/template_mapping"
                      }
                    }
                  ]
                }
              }
            },
            "static_mapping": {
              "type": "object",
              "allOf": [
                {
                  "$ref": "#/$defs/mapping_commons"
                }
              ],
              "required": [
                "message_mapping"
              ],
              "properties": {
                "message_mapping": {
                  "oneOf": [
                    {
                      "$ref": "#/$defs/message_mapping"
                    },
                    {
                      "type": "array",
                      "items": {
                        "$ref": "#/$defs/message_mapping"
                      },
                      "minItems": 1
                    }
                  ]
                }
              }
            },
            "message_mapping": {
              "type": "object",
              "required": [
                "message",
                "mapped_message"
              ],
              "properties": {
                "message": {
                  "type": "string",
                  "minLength": 1
                },
                "mapped_message": {
                  "type": "string",
                  "minLength": 1
                }
              }
            },
            "template_mapping": {
              "type": "object",
              "allOf": [
                {
                  "$ref": "#/$defs/mapping_commons"
                }
              ],
              "required": [
                "mapping_template"
              ],
              "properties": {
                "mapping_template": {
                  "type": "string",
                  "minLength": 1
                },
                "suppressions": {
                  "type": "array",
                  "items": {
                    "type": "string"
                  },
                  "default": [
                  ]
                }
              }
            },
            "mapping_commons": {
              "type": "object",
              "required": [
                "mapped_topic"
              ],
              "properties": {
                "mapped_topic": {
                  "type": "string",
                  "pattern": "(\\{\\{\\s*[^\\{\\}]+?\\s*\\}\\}|\\{\\{\\s*#\\s*[^\\{\\}]+?\\s*\\}\\}|\\{\\{\\s*/\\s*[^\\{\\}]+?\\s*\\}\\})|^[^#+]*$",
                  "minLength": 1
                },
                "retain": {
                  "type": "boolean",
                  "default": false
                },
                "qos": {
                  "type": "integer",
                  "minimum": 0,
                  "maximum": 2,
                  "default": 0
                },
                "delay": {
                  "type": "number",
                  "oneOf": [
                    { "const": -1 },
                    { "minimum": 0 }
                  ],
                  "default": -1
                }
              }
            }
          }
        }
      }
    }
  }
}

=== SNodeC/mqttsuite/mapfile.json
{
  "connection": {
    "clean_session": true,
    "client_id": "MQTT-Integrator",
    "keep_alive": 60,
    "password": "Password",
    "username": "Username",
    "will_message": "Last Will",
    "will_qos": 0,
    "will_retain": false,
    "will_topic": "will/topic"
  },
  "discover_prefix": "iotempower",
  "mapping": {
    "plugins": [
      "libmqtt-mapping-plugin-double.so",
      "libmqtt-mapping-plugin-storage.so"
    ],
    "topic_level": [
      {
        "name": "rfid",
        "topic_level": [
          {
            "name": "button1",
            "subscription": {
              "qos": 2,
              "static": [
                {
                  "mapped_topic": "mapping/value",
                  "message_mapping": [
                    {
                      "mapped_message": "on",
                      "message": "pressed"
                    },
                    {
                      "mapped_message": "off",
                      "message": "released"
                    }
                  ]
                },
                {
                  "mapped_topic": "strip/strip1/rgb/set",
                  "message_mapping": {
                    "mapped_message": "front red",
                    "message": "pressed"
                  }
                },
                {
                  "mapped_topic": "chain/strip1/rgb/set",
                  "message_mapping": {
                    "mapped_message": "front red",
                    "message": "pressed"
                  }
                },
                {
                  "mapped_topic": "strip/strip1/brightness/set",
                  "message_mapping": {
                    "mapped_message": "0",
                    "message": "released"
                  }
                },
                {
                  "mapped_topic": "chain/strip1/brightness/set",
                  "message_mapping": {
                    "mapped_message": "0",
                    "message": "released"
                  }
                }
              ],
              "type": "binary_sensor"
            }
          },
          {
            "name": "rfid",
            "subscription": {
              "type": "new rfid reader",
              "value": {
                "mapped_topic": "chain/strip1/rgb/set",
                "mapping_template": "front {{ message }}"
              }
            },
            "topic_level": {
              "name": "uid",
              "subscription": {
                "type": "rfid reader",
                "value": [
                  {
                    "mapped_topic": "strip/strip1/rgb/set",
                    "mapping_template": "{% if message == \"739bb7a6\" %}front green{% endif %}",
                    "suppressions": [
                      ""
                    ]
                  },
                  {
                    "mapped_topic": "strip/strip1/brightness/set",
                    "mapping_template": "{% if message == \"none\" %}0{% endif %}",
                    "suppressions": [
                      ""
                    ]
                  },
                  {
                    "mapped_topic": "chain/strip1/brightness/set",
                    "mapping_template": "{% if message == \"none\" %}0{% endif %}",
                    "suppressions": [
                      ""
                    ]
                  }
                ]
              }
            }
          }
        ]
      },
      {
        "name": "mapping",
        "topic_level": [
          {
            "name": "value",
            "subscription": {
              "value": {
                "mapped_topic": "mapping/json",
                "mapping_template": "{\"state\":\"{{message}}\"}"
              }
            }
          },
          {
            "name": "json",
            "subscription": {
              "json": {
                "mapped_topic": "chain/onboard/set",
                "mapping_template": "{% if message.state == \"on\" %}on{% else if message.state == \"off\" %}off{% endif %}"
              }
            }
          }
        ]
      },
      {
        "name": "temperature",
        "topic_level": [
          {
            "name": "celsius",
            "topic_level": {
              "name": "set",
              "subscription": {
                "qos": 2,
                "value": [
                  {
                    "mapped_topic": "temperature/celsius",
                    "mapping_template": "{{ round(float(message), 2) }}",
                    "qos": 2,
                    "retain": true
                  },
                  {
                    "mapped_topic": "temperature/kelvin",
                    "mapping_template": "{{ round(float(message) + 273.15, 2) }}",
                    "qos": 1,
                    "retain": true
                  },
                  {
                    "mapped_topic": "temperature/farenheit",
                    "mapping_template": "{{ round(float(message) * 1.8 + 32, 2) }}",
                    "qos": 2,
                    "retain": true
                  }
                ]
              }
            }
          },
          {
            "name": "kelvin",
            "topic_level": {
              "name": "set",
              "subscription": {
                "qos": 2,
                "value": [
                  {
                    "mapped_topic": "temperature/celsius",
                    "mapping_template": "{{ round(float(message) - 273.15, 2) }}",
                    "qos": 2,
                    "retain": true
                  },
                  {
                    "mapped_topic": "temperature/kelvin",
                    "mapping_template": "{{ round(float(message), 2) }}",
                    "qos": 1,
                    "retain": true
                  },
                  {
                    "mapped_topic": "temperature/farenheit",
                    "mapping_template": "{{ round((float(message) - 273.15) * 1.8 + 32, 2) }}",
                    "qos": 2,
                    "retain": true
                  }
                ]
              }
            }
          },
          {
            "name": "farenheit",
            "topic_level": {
              "name": "set",
              "subscription": {
                "qos": 2,
                "value": [
                  {
                    "mapped_topic": "temperature/celsius",
                    "mapping_template": "{{ round((float(message) - 32) / 1.8, 2) }}",
                    "qos": 2,
                    "retain": true
                  },
                  {
                    "mapped_topic": "temperature/kelvin",
                    "mapping_template": "{{ round((float(message) - 32) / 1.8 + 273.15, 2) }}",
                    "qos": 1,
                    "retain": true
                  },
                  {
                    "mapped_topic": "temperature/farenheit",
                    "mapping_template": "{{ round(float(message), 2) }}",
                    "qos": 2,
                    "retain": true
                  }
                ]
              }
            }
          }
        ]
      },
      {
        "name": "double",
        "subscription": {
          "qos": 2,
          "value": {
            "mapped_topic": "{{ topic + \"_result\" }}",
            "mapping_template": "{{ double(float(message)) + recall_as_int(topic + \"currentValue\") }}{{ store(topic + \"currentValue\", message) }}"
          }
        }
      },
      {
        "name": "v3",
        "topic_level": {
          "name": "test-application-voc@ttn",
          "topic_level": {
            "name": "devices",
            "topic_level": {
              "name": "+",
              "topic_level": {
                "name": "up",
                "subscription": {
                  "json": {
                    "mapped_topic": "ttn/{{message.end_device_ids.device_id}}",
                    "mapping_template": "{\"application\":\"{{message.end_device_ids.application_ids.application_id}}\",\"device\":\"{{message.end_device_ids.device_id}}\",\"data\":{{ message.uplink_message.decoded_payload }}}"
                  }
                }
              }
            }
          }
        }
      },
      {
        "name": "zigbee2mqtt",
        "topic_level": [
          {
            "name": "Philips-T-01",
            "topic_level": {
              "name": "action",
              "subscription": {
                "static": [
                  {
                    "mapped_topic": "zigbee2mqtt/Philips-CA-All/set",
                    "message_mapping": [
                      {
                        "mapped_message": "{ \"state\": \"ON\" }",
                        "message": "on_press"
                      },
                      {
                        "mapped_message": "{ \"brightness_step_onoff\": 32, \"transition\": 1 }",
                        "message": "up_press"
                      },
                      {
                        "mapped_message": "{ \"brightness_step_onoff\": -32, \"transition\": 1 }",
                        "message": "down_press"
                      },
                      {
                        "mapped_message": "{ \"state\": \"OFF\" }",
                        "message": "off_press"
                      }
                    ]
                  }
                ]
              }
            }
          },
          {
            "name": "Philips-M-01",
            "subscription": {
              "json": {
                "mapped_topic": "zigbee2mqtt/Philips-CA-All/set",
                "mapping_template": "{% if message.occupancy == true %}{ \"state\": \"ON\" }{% endif %}",
                "suppressions": [
                  ""
                ]
              }
            }
          }
        ]
      }
    ]
  },
  "meta": {
    "created": "2026-03-18T14:13:54Z",
    "version": "1773843234"
  }
}
